### ISSUE TITLE
Validate link.call

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#120]
``` js
/home/ionicabizau/Documents/_engineApps/engine/lib/module/module.js:90
            link.call.call(self, err, data, sendHandler(self._name, self));
                      ^
TypeError: Cannot call method 'call' of undefined
    at EventEmitter.<anonymous> (/home/ionicabizau/Documents/_engineApps/engine/lib/module/module.js:90:23)
    at EventEmitter.emit (events.js:98:17)
    at WebSocket.<anonymous> (/home/ionicabizau/Documents/_engineApps/engine/lib/project/server.js:139:21)
    at WebSocket.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/WebSocket.js:682:10)
    at Receiver.opcodes.1.finish (/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/Receiver.js:391:14)
    at Receiver.expectHandler (/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/WebSocket.js:663:22)
    at Socket.emit (events.js:95:17)
ionicabizau@laptop:~/Documents/_engineApps/engine$ 
```

**Comment by ottiker** [comment]
That happens, when the `method` of an module doesn't exists, but is configured in the `links` config of an instance.

**Comment by IonicaBizau** [comment]
Yes, but we need to check that in engine, I guess...

**Comment by ottiker** [comment]
Yes, an error should be returned, instead of crashing the process.
