### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#123]
This happened after starting service app, on first request (http://github.jillix.service.jillix.ch:10001/build/github.jillix.service/). Also, only the navbar was loaded (and CSS).

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:160:15)
    at EventEmitter.once (events.js:185:8)
    at /home/ionicabizau/Documents/_engineApps/engine/lib/module/module.js:331:33
    at Object.Cache.get (/home/ionicabizau/Documents/_engineApps/engine/lib/cache/comp.js:88:20)
    at /home/ionicabizau/Documents/_engineApps/engine/lib/module/module.js:318:21
    at /home/ionicabizau/Documents/_engineApps/engine/lib/cache/comp.js:129:13
    at /home/ionicabizau/Documents/_engineApps/engine/node_modules/fs-extra/node_modules/jsonfile/lib/jsonfile.js:23:5
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by ottiker** [comment]
This message can come, when more than 11 event listeners are added on the server side.
