### ISSUE TITLE
Do not add commit hashes for remote scripts

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#74]
``` sh
.../engine/lib/project/router.js:62              
            libs.push(z_path);                                                       
                 ^                                                                   
TypeError: Cannot call method 'push' of undefined                                    
    at /home/ionicabizau/Documents/_engineApps/engine/lib/project/router.js:62:18    
    at /home/ionicabizau/Documents/_engineApps/engine/lib/utils/fingerprint.js:99:9  
    at ChildProcess.exithandler (child_process.js:646:7)                             
    at ChildProcess.emit (events.js:98:17)                                           
    at maybeClose (child_process.js:756:16)                                          
    at Socket.<anonymous> (child_process.js:969:11)                                  
    at Socket.emit (events.js:95:17)                                                 
    at Pipe.close (net.js:465:12)                                                    
```
#69

**Comment by ottiker** [comment]
Fixed in 2e9f45bc3c1421392968010ac9928c4951ed5d5a
